package CalculModule;


/**
* CalculModule/CalculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* jeudi 7 d�cembre 2023 13 h 28 WAT
*/

public interface CalculOperations 
{
  double addition (double a, double b);
  double multiplication (double a, double b);
  double soustraction (double a, double b);
  double division (double a, double b);
} // interface CalculOperations
