package CalculModule;


/**
* CalculModule/Calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* jeudi 7 décembre 2023 13 h 28 WAT
*/

public interface Calcul extends CalculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calcul
