package CalculModule;

/**
* CalculModule/CalculHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* jeudi 7 décembre 2023 13 h 28 WAT
*/

public final class CalculHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculModule.Calcul value = null;

  public CalculHolder ()
  {
  }

  public CalculHolder (CalculModule.Calcul initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculModule.CalculHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculModule.CalculHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculModule.CalculHelper.type ();
  }

}
